# Generated by Django 4.0 on 2022-06-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(0, ''), (1, '紧急'), (2, '临时'), (3, '重要')], default=1, verbose_name='任务级别')),
                ('title', models.CharField(max_length=64, verbose_name='任务标题')),
                ('detail', models.TextField(verbose_name='任务详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='负责人')),
            ],
        ),
    ]
