# Generated by Django 4.0 on 2022-06-06 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
